# -*- coding:utf-8 -*-



words_dict = {
    'brisk': 'adj.兴隆的，繁忙活跃的；轻快的',
    'brief': 'adj.简短的，简洁的；短时间的，短暂的',
    'browse': 'v.浏览；吃草，放牧； n.浏览；嫩草，嫩叶',
    'aggrevate': 'vt.加重,加剧，恶化',
    'aggregate': 'n.总数，总计  adj.总数的，总计的   v.总计，合计',
    'aggressive': 'adj.好斗的，侵略的；积极进取的，活跃有为的',
    'agitate': 'v.搅动；使激动，使暴躁',
    'aid': 'vt.援助，帮助；   n.援助，救济',
    'alarm': 'n.惊恐，忧虑；警报，警钟，告警器   v.使惊恐，使忧虑；向....报警',
    'alien': 'adj.陌生的，外国的',
    'alienate': 'v.排斥，疏远；使不友好；使疏远',
    'allocate': 'vt.分配，分派；把.....拨给',
    'alternate': 'v.交替,轮流；    adj.交替的，轮流的',
    'alternative': 'adj.两者挑一的,可供选择的；  n.可供选择的事物，替换物',
    'comparable': 'adj.可比较的，比得上，类似的',
    'comparative': 'adj.比得上，相比的；相比之下的',
    'compare': 'v.比较，对照',
    'comparasion': 'n.比较，对比，比喻，比拟',
    'compel': 'vt.迫使，强迫',
    'conpensate': 'v.补偿，赔偿',
    'compete': 'vt.比赛，竞争',
    'competition': 'n.竞争，比赛',
    'competitive': '竞争的,比赛的',
    'competent': 'adj.有能力的，能胜任的',
    'compile': 'vt.收集；汇编；编制；编纂',
    'complain': 'vi.抱怨,申诉',
    'complement': 'vt.补充，补足    n.补足物，余数，补语',
    'complete': 'vt.结束，完成   adj.完整的，完全的',
    'complex': 'adj.复杂的，费解的；合成的，综合的',
    'complicate': 'vt.使变复杂',
    'complicated': 'adj.错综复杂的,麻烦的',
    'comply': 'vt.遵从，顺从，服从',
    'compliment': 'n.问候，致意;称赞，恭维',
    'differ': 'vi.与.....不同',
    'difference': 'n.类别，不同，变化;意见分歧',
    'diffuse': 'v.扩散；传播，散布；   adj.弥散的，四散的，冗长的，漫无边际的',
    'emphasis': 'n.强调，重点',
    'emphasize': 'vt.强调',
    'employ': 'vt.雇佣，使用',
    'employee': 'n.雇员，雇工',
    'employer': 'n.雇主',
    'employment': 'n.雇佣，使用',
    'enable': 'vt.使能够，使能成为',
    'encounter': 'v.冲突，交战;  n.意外；遇见',
    'encourage': 'v.鼓励，支持',
    'endeavor': 'v.努力，尽力',
    'endorse': 'v.赞同，支持，认可',
    'indicate': 'vt.指出，指示；迹象，暗示',
    'indication': 'n.指出，指示；迹象，暗示',
    'indicative': 'adj.指示的，暗示的',
    'outrage': 'n.伤害，虐待；愤怒；  vt.凌辱，引起.....义愤；违反，违法',
    'outset': 'n.开始，开端',
    'outside': 'n.外部，外表； adj.在外边，向外的; adv.在外面，向外面；在户外',
    'outward': 'adv.向外，在外;  adj.向外的；外面的，外表的',
    'special': 'adj.特殊的，专门的',
    'specialist': 'n.专家',
    'specialize': 'v.专攻，专门研究；专注于',
    'specialty': 'n.特制品，特产，专业，专长',
    'species': 'adj.种类',
    'specific': 'adj.具体的，明确的',
    'specification': 'n.明确,详述',
    'specify': 'vt.具体指定,详细说明',
    'speculate': 'v.推测，推断；投机',
    'acclaim': 'n.喝彩，欢呼；  v.赞扬，称赞',
    'accommodate': 'v.使适应,使符合一致;帮助，给.....提供住处',
    'accommodation': 'n.住宿，留宿',
    'accompany': 'vt.陪伴,伴随',
    'accomplish': 'vt.达到，实现，完成',
    'account': 'n.账户，账单；   v.认为，视为',
    'accountant': 'n.会计员，会计师',
    'bias': 'n.偏见；偏重；  vt.使有偏见的，偏向',
    'bid': 'v.祝愿，命令',
    'bill': 'n.账单；招贴，广告',
    'billion': 'n.十亿',
    'birth': 'n.出生，分娩',
    'charge': 'v.要价，收费；使充电，使充满；  n.负荷，电荷；价钱，费用',
    'charm': 'n.美貌，妩媚；   v.使陶醉，迷住',
    'demand': 'vt.要求;查问',
    'democracy': 'n.民主，民主制；民主国家',
    'democratic': 'adj.民主的',
    'demographic': 'adj.人口统计学的，人口统计的',
    'demostrate': 'v.论证，证明，说明',
    'denote': 'vt.表示，是....的标志',
    'denial': 'n.否认，拒绝',
    'deny': 'v.否认，拒绝',
    'department': 'n.系，部，局',
    'depend': 'vt.取决于，依靠',
    'dependent': 'adj.依靠的，依赖的',
    'deposit': 'v.使沉积；存放  n.沉淀物',
    'depress': 'vt.使沮丧，使消极；按下，压下',
    'emerge': 'v.出现，浮现',
    'emergency': 'n.紧急情况，突然事件',
    'eminent': 'adj.杰出的，著名的',
    'emotion': 'n.情绪，情感',
    'fear': 'vt.害怕，畏惧    n.害怕，担心',
    'fearful': 'adj.担心的，可怕的',
    'feature': 'n.特色,特征',
    'federal': 'adj.联邦的',
    'federation': 'n.联邦，同盟',
    'feed': 'v.喂养，饲养',
    'feedback': 'n.反馈,反馈的意见',
    'feeling': 'n.感情，心情',
    'fertile': 'adj.肥沃的，富饶的',
    'goal': 'n.目标，目的',
    'goods': 'n.商品，货物，财产',
    'govern': 'v.管理，统治；决定，支配',
    'government': 'n.政府，内阁；统治，管理，支配；政治',
    'governor': 'n.总督，省长',
    'gradual': 'adj.逐渐的，逐步的',
    'graduate': 'v.毕业，获得学位；  adj.有学位的，毕业的，研究生的；   n.毕业生，获得学位者',
    'grand': 'adj.盛大的，豪华的；重大的，主要的',
    'grant': 'vt.同意,准予；授予，给予',
    'heap': 'n.一大堆，大量，许多；   vt.堆积；给与，装满',
    'heal': 'v.之余，愈合；调停，止息，消除，克服',
    'health': 'n.健康，健康状况；卫生',
    'healthy': 'adj.健康的，健壮的；有益健康的，卫生的',
    'hesitate': 'v.犹豫，踌躇；含糊',
    'highlight': 'vt.使显著，使突出    n.最有意思或最精彩的部分',
    'highthy': 'adv.高度地，很，非常；赞许低',
    'immediate': 'adj.立刻的，即时的；直接的，最接近的',
    'immense': 'adj.广大的，扩大的',
    'immerse': 'vt.（in）使浸没,使沉浸在，使专注于；',
    'immigrant': 'n.移民,侨民',
    'imminent': 'adj.即将发生的，临近的',
    'immune': 'adj.免除的，豁免的的',
    'likehood': 'n.可能性',
    'likewise': 'adv.同样地，照样地；又，也',
    'selfish': 'adj.自私的，利己的'
}