# -*- coding:utf-8 -*-



words_dict = {
    'brisk': 'adj.兴隆的，繁忙活跃的；轻快的',
    'brief': 'adj.简短的，简洁的；短时间的，短暂的',
    'browse': 'v.浏览；吃草，放牧； n.浏览；嫩草，嫩叶',
    'aggregate': 'n.总数，总计  adj.总数的，总计的   v.总计，合计',
    'aggressive': 'adj.好斗的，侵略的；积极进取的，活跃有为的',
    'agitate': 'v.搅动；使激动，使暴躁',
    'aid': 'vt.援助，帮助；   n.援助，救济',
    'alarm': 'n.惊恐，忧虑；警报，警钟，告警器   v.使惊恐，使忧虑；向....报警',
    'alien': 'adj.陌生的，外国的',
    'alienate': 'v.排斥，疏远；使不友好；使疏远',
    'allocate': 'vt.分配，分派；把.....拨给',
    'alternate': 'v.交替,轮流；    adj.交替的，轮流的',
    'alternative': 'adj.两者挑一的,可供选择的；  n.可供选择的事物，替换物',
    'comparable': 'adj.可比较的，比得上，类似的',
    'comparative': 'adj.比得上，相比的；相比之下的',
    'compare': 'v.比较，对照',
    'comparison': 'n.比较，对比，比喻，比拟',
    'compel': 'vt.迫使，强迫',
    'compensate': 'v.补偿，赔偿',
    'compete': 'vt.比赛，竞争',
    'competition': 'n.竞争，比赛',
    'competitive': '竞争的,比赛的',
    'competent': 'adj.有能力的，能胜任的',
    'compile': 'vt.收集；汇编；编制；编纂',
    'complain': 'vi.抱怨,申诉',
    'complement': 'vt.补充，补足    n.补足物，余数，补语',
    'complete': 'vt.结束，完成   adj.完整的，完全的',
    'complex': 'adj.复杂的，费解的；合成的，综合的',
    'complicate': 'vt.使变复杂',
    'complicated': 'adj.错综复杂的,麻烦的',
    'comply': 'vt.遵从，顺从，服从',
    'compliment': 'n.问候，致意;称赞，恭维',
    'differ': 'vi.与.....不同',
    'difference': 'n.类别，不同，变化;意见分歧',
    'diffuse': 'v.扩散；传播，散布；   adj.弥散的，四散的，冗长的，漫无边际的',
    'emphasis': 'n.强调，重点',
    'emphasize': 'vt.强调',
    'employ': 'vt.雇佣，使用',
    'employee': 'n.雇员，雇工',
    'employer': 'n.雇主',
    'employment': 'n.雇佣，使用',
    'enable': 'vt.使能够，使能成为',
    'encounter': 'v.冲突，交战;  n.意外；遇见',
    'encourage': 'v.鼓励，支持',
    'endeavor': 'v.努力，尽力',
    'endorse': 'v.赞同，支持，认可',
    'indicate': 'vt.指出，指示；迹象，暗示',
    'indication': 'n.指出，指示；迹象，暗示',
    'indicative': 'adj.指示的，暗示的',
    'outrage': 'n.伤害，虐待；愤怒；  vt.凌辱，引起.....义愤；违反，违法',
    'outset': 'n.开始，开端',
    'outside': 'n.外部，外表； adj.在外边，向外的; adv.在外面，向外面；在户外',
    'outward': 'adv.向外，在外;  adj.向外的；外面的，外表的',
    'special': 'adj.特殊的，专门的',
    'specialist': 'n.专家',
    'specialize': 'v.专攻，专门研究；专注于',
    'specialty': 'n.特制品，特产，专业，专长',
    'species': 'adj.种类',
    'specific': 'adj.具体的，明确的',
    'specification': 'n.明确,详述',
    'specify': 'vt.具体指定,详细说明',
    'speculate': 'v.推测，推断；投机',
    'acclaim': 'n.喝彩，欢呼；  v.赞扬，称赞',
    'accommodate': 'v.使适应,使符合一致;帮助，给.....提供住处',
    'accommodation': 'n.住宿，留宿',
    'accompany': 'vt.陪伴,伴随',
    'accomplish': 'vt.达到，实现，完成',
    'account': 'n.账户，账单；   v.认为，视为',
    'accountant': 'n.会计员，会计师',
    'bias': 'n.偏见；偏重；  vt.使有偏见的，偏向',
    'bid': 'v.祝愿，命令',
    'bill': 'n.账单；招贴，广告',
    'billion': 'n.十亿',
    'birth': 'n.出生，分娩',
    'charge': 'v.要价，收费；使充电，使充满；  n.负荷，电荷；价钱，费用',
    'charm': 'n.美貌，妩媚；   v.使陶醉，迷住',
    'demand': 'vt.要求;查问',
    'democracy': 'n.民主，民主制；民主国家',
    'democratic': 'adj.民主的',
    'demographic': 'adj.人口统计学的，人口统计的',
    'demonstrate': 'v.论证，证明，说明',
    'denote': 'vt.表示，是....的标志',
    'denial': 'n.否认，拒绝',
    'deny': 'v.否认，拒绝',
    'department': 'n.系，部，局',
    'depend': 'vt.取决于，依靠',
    'dependent': 'adj.依靠的，依赖的',
    'deposit': 'v.使沉积；存放  n.沉淀物',
    'depress': 'vt.使沮丧，使消极；按下，压下',
    'emerge': 'v.出现，浮现',
    'emergency': 'n.紧急情况，突然事件',
    'eminent': 'adj.杰出的，著名的',
    'emotion': 'n.情绪，情感',
    'fear': 'vt.害怕，畏惧    n.害怕，担心',
    'fearful': 'adj.担心的，可怕的',
    'feature': 'n.特色,特征',
    'federal': 'adj.联邦的',
    'federation': 'n.联邦，同盟',
    'feed': 'v.喂养，饲养',
    'feedback': 'n.反馈,反馈的意见',
    'feeling': 'n.感情，心情',
    'fertile': 'adj.肥沃的，富饶的',
    'goal': 'n.目标，目的',
    'goods': 'n.商品，货物，财产',
    'govern': 'v.管理，统治；决定，支配',
    'government': 'n.政府，内阁；统治，管理，支配；政治',
    'governor': 'n.总督，省长',
    'gradual': 'adj.逐渐的，逐步的',
    'graduate': 'v.毕业，获得学位；  adj.有学位的，毕业的，研究生的；   n.毕业生，获得学位者',
    'grand': 'adj.盛大的，豪华的；重大的，主要的',
    'grant': 'vt.同意,准予；授予，给予',
    'heap': 'n.一大堆，大量，许多；   vt.堆积；给与，装满',
    'heal': 'v.治愈，愈合；调停，止息，消除，克服',
    'health': 'n.健康，健康状况；卫生',
    'healthy': 'adj.健康的，健壮的；有益健康的，卫生的',
    'hesitate': 'v.犹豫，踌躇；含糊',
    'highlight': 'vt.使显著，使突出    n.最有意思或最精彩的部分',
    'highly': 'adv.高度地，很，非常；赞许低',
    'immediate': 'adj.立刻的，即时的；直接的，最接近的',
    'immense': 'adj.广大的，扩大的',
    'immerse': 'vt.（in）使浸没,使沉浸在，使专注于；',
    'immigrant': 'n.移民,侨民',
    'imminent': 'adj.即将发生的，临近的',
    'immune': 'adj.免除的，豁免的的',
    'likelihood': 'n.可能性',
    'likewise': 'adv.同样地，照样地；又，也',
    'selfish': 'adj.自私的，利己的',
    'dreadful':  'adj.可怕的',
    'handicap':  'n.残障,弊端' ,
    'properly': 'adv.正确的',
    'handled':  'v.处理',
    'driving force':    '驱动力',
    'glowing':  'adj.辉煌的, 发光的' ,
    'paralleled':   'n.平行    adj.相似的' ,
    'prosperous':  'adj.繁荣昌盛',
    'painstaking':   'adj.艰苦的',
    'domestic': 'adj.国内的',
    'workforce': 'n.劳动力',
    'impetus': 'n.动力',
    'potential': 'adj.潜在的',
    'manifested': 'adj.明显的',
    'primacy': 'n.首要地位;首要;至高无上,优势',
    'inevitable': 'adj.不可避免的',
    'retreat from':  '退出',
    'shrunk':  'v.缩水,收缩',
    'textile': 'n.纺织品',
    'sweep into': '把…扫入…;昂然走进',
    'rope': 'n. 粗绳; 线缆;',
    'on the ropes': '处境艰难;即将放弃;濒临失败;走投无路',
    'invent': 'vt.发明;',
    'semiconductor': 'n.半导体',
    'take over': '接管',
    'casualty': '伤亡',
    'withdraw': 'v.撤退;撤回',
    'prosperity':  'n.兴旺;繁荣',
    'crisis' : 'n.危机',
    'criticism':   'n.评论,评论文章',
    'inquiry':  'n.调查;查询;询问;打听;(官方的)查问;询问过程',
    'while':   '尽管,强烈对比 !',
    'sensational':   'adj.轰动的;引起哗然的;',
    'solid':   'n.固体   adj.稳固的;坚固的;坚硬的',
    'solely':  'adv.唯一地;仅;',
    'obvious':   'adj.明显的',
    'devalued':   'adj.贬值的',
    'business cycle':    '商业周期',
    'self-doubt':   '自我怀疑',
    'blind':  'adj.盲目的',
    'yielded':   'v.出产(作物);产生(收益、效益等);',
    'yielded to':  '屈服于',
    'diet':   'n.饮食  v.节食',
    'intense':   'adj.激烈的',
    'cooperation':   'n.合作',
    'pave':  'vt.铺路',
    'beam':   'n.(光线的)束,柱;横梁;   v.微笑;发光,照射' ,
    'deprive': 'v.剥夺,使丧失',
    'derive':  'v.取得,得到',
    'describe': 'vt.形容,描述',
    'description': 	'n.描述,形容;种类,类型',
    'deserve': 	'vt.值得,应得',
    'design': 	'v.设计,绘制;		n.设计,图样',
    'designate': 'vt.指明,标明;指定,指派',
    'desirable': 'adj.称心的,合意的',
    'desire': 'vt.希望,渴望',
    'flaw': 'n.裂缝;缺陷,缺点',
    'flexible': 'adj.柔韧的;易弯曲的;可变通的',
    'fling': 'v.扔,抛,丢',
    'flourish': 'n.流畅的曲线;炫耀 	v.茂盛,繁荣,兴旺;挥舞,舞动;炫耀',
    'grow-up': 'adj.成熟的人,成人的',
    'growth': 'n.生长,增长,发展',
    'hint': 'n.暗示;建议;线索 		v.暗示,示意',
    'hitherto': 'adv.到目前为止,迄今',
    'impact': 'vt.压紧;对某件事物有影响  n.冲击,撞击',
    'impair': 'vt.削弱,减少',
    'impart': 'vt.传授;给予',
    'implement': 'v.实施,执行,贯彻  n.工具,器具',
    'implication': 'n.含意,暗示',
    'implicit': 'adj.含蓄的;无疑问的,绝对的',
    'imply': 'vt.意味着,暗示',
    'impose': 'v.征税,加负担于;把...强加于',
    'impress': 'v.印,盖印;留下印象;   n.压痕,印记',
    'impression': 'n.印象,感想',
    'impressive': 'adj.给人印象深刻的,感人的',
    'improve': 	'v.改善,增进,提高',
    'impulse': 'n.推动,驱动;冲动',
    'limit': 	'n.界限,范围   v.限制',
    'limitation': 'n.限制,局限性',
    'limited': 'adj.有限的,被限制的',
    'origin': 	'n.起源,由来',
    'original': 'adj.最初的,原始的,原先的   n.原物,原作',
    'originate': 'v.发源,产生,引起',
    'petition': 'n.请愿,请愿书;  v.向...请愿',
    'phase':  'n.阶段,时期',
    'phenomenon': 'n.现象;非凡的人',
    'philosopher': 'n.哲学家',
    'philosophy': 'n.哲学',
    'phrase': 	'n.短语,词语',
    'physical': 'adj.自然科学的,物理的;肉体的,身体的',
    'physician': 'n.医师,内科医生',
    'pierce': 	'vt.刺穿,刺入;看破,识破',
    'corporate': 'adj.公司的,社团的',
    'corporation': 'n.公司;法人',
    'reason': 'n.理由,原因;道理',
    'reasonable': 	'adj.合理的,有道理的',
    'recent':  'adj.最近的',
    'serve': 'v.服务',
    'servant': 'n.佣人,仆人',
    'setback': 'n.挫折,退步;复发;延迟',
    'settle': 	'vi.安定,安顿',
    'settlement': 'n.解决,决定,调停;移民地',
    'several': 	'adj.各自的  pron.几个',
    'severe': 'adj.严格的',
    'shape': 'n.形状,外形  v.使成形',
    'sharp':  'adj.锋利的,锐利的  adv.准时的',
    'shelter': 'n.遮蔽物,躲避处  n.遮蔽,庇护',
    'sophisticated': 'adj.老练的,复杂的',
    'sovereign': 'n.君主,统治  adj.至高无上的',
    'sow': 	'vt.播种',
    'toll': 'n.通行税;代价  v.鸣钟',
    'tone': 'n.音色,风气,气氛',
    'topic': 'n.话题,主题'
}

